format = """
[  ](fg:#cfc9c2 bg:#1a1b26)\
[](bg:#1a1b26 fg:#414868)\
$directory\
[](bg:#414868 fg:#1a1b26)\
$git_branch\
$git_status\
[](bg:#1a1b26 fg:#414868)\
$python\
$c\
$conda\
[](bg:#414868 fg:#000000)\
\n$character"""

[directory]
style = "fg:#c0caf5 bg:#414868"
format = "[ $path ]($style)"
fish_style_pwd_dir_length = 1
home_symbol = "󰟒"
truncation_length = 8
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = "󰇚"
"Music" = ""
"Projects" = ""
"Pictures" = ""

[git_branch]
symbol = ""
style = "bg:#1a1b26 fg:#e0af68"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#1a1b26 fg:#e0af68"
format = "[ ($all_status $ahead_behind) ]($style)"

[python]
symbol = ""
style = "bg:#414868 fg:#c0caf5"
format = "[ $symbol ($version) ]($style)"

[c]
symbol = ""
style = "bg:#414868 fg:#c0caf5"
format = "[ $symbol ($version) ]($style)"

[conda]
style = "bg:#414868 fg:#c0caf5"
format = '[ $symbol $environment ]($style)'

[character]
success_symbol="[~](#e0af86)"
error_symbol="[](#f7768e)"
